SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) as 'count'
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE -- ANIMAL_TYPE으로 그룹화하여.
ORDER BY CASE ANIMAL_TYPE -- 정렬하라 ANIMAL_TYPE 조건에 따라
WHEN 'Cat' THEN 1 -- ANIMAL_TYPE이 'Cat'일 때, 우선순위 1
WHEN 'Dog' THEN 2 -- ANIMAL_TYPE이 'Dog'일 때, 우선순위 2
ELSE 3 -- 그 외 ANIMAL_TYPE은 우선순위 3
END -- CASE 문을 끝낸다
