SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM ANIMAL_INS INS
INNER JOIN ANIMAL_OUTS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
-- 문자열을 다룰 때, "특정문자열%", "%특정문자열", "%특정문자열%", "특정문자열_특정문자열" 처럼 조건을 줄 수 있다.
WHERE INS.SEX_UPON_INTAKE LIKE "Intact%" and OUTS.SEX_UPON_OUTCOME NOT LIKE "Intact%"
ORDER BY INS.ANIMAL_ID
