-- ANIMAL_ID, NAME을 선택하라. ANIMAL_INS로부터. 다만 INTAKE_CONDITION이 'Sick'의 값인 것만. ANIMAL_ID 기준으로 정렬
-- '='와 같은 것은 'LIKE'.
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS WHERE INTAKE_CONDITION = 'Sick' ORDER BY ANIMAL_ID
