-- 안 되는 코드. 왜지?
/*
SELECT HOUR(DATETIME), COUNT(HOUR(DATETIME))
FROM ANIMAL_OUTS 
GROUP BY HOUR(DATETIME) 
HAVING HOUR(DATETIME) >= 9 and HOUR(DATETIME) <= 19
ORDER BY HOUR(DATETIME)

SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR >=9 and HOUR < 20
GROUP BY HOUR
ORDER BY HOUR
*/

-- 쿼리 실행 순서
-- FROM, WEHRE, GROUP BY, HAVING, SELECT, ORDER BY
-- HAVING의 컬럼은 SELECT에서 가져온다. 그리고 WHERE의 컬럼은 FROM에서 가져온다.
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >=9 and HOUR(DATETIME) < 20
GROUP BY HOUR
ORDER BY HOUR
